projects:
  Bark Detector App:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        region: ap-southeast-2
        apiId: coqczpqf7ffitelz5urwidobpa
extensions:
  amplify:
    version: 3
